name: Download Latest Stocks

# Controls when the action will run.
on:
  schedule:
    # Run at midnight UTC (5 pm PDT) Mon thru Fri (temp change to 11:30 pm UTC for testing)
    - cron: "30 23 * * 1-5"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # set the current date in environment to be used for appending to filenames in subsequent steps
      - name: current-date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Generate NASDAQ Data
      - name: make-nasdaq-directory
        run: mkdir -p $GITHUB_WORKSPACE/nasdaq
      - name: get-nasdaq
        run: "curl --user-agent 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:85.0) Gecko/20100101 Firefox/85.0' https://api.nasdaq.com/api/screener/stocks\\?tableonly\\=true\\&limit\\=25\\&offset\\=0\\&exchange\\=nasdaq\\&download\\=true > /tmp/nasdaq.json"
      - name: gen-nasdaq-stock-tickers-json
        run: "cat /tmp/nasdaq.json | jq '.data.rows' > $GITHUB_WORKSPACE/datafiles/nasdaq/nasdaq_full_tickers-${{ env.DATE }}.json"

      # Generate NYSE Data
      - name: make-nyse-directory
        run: mkdir -p $GITHUB_WORKSPACE/nyse
      - name: get-nyse
        run: "curl --user-agent 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:85.0) Gecko/20100101 Firefox/85.0' https://api.nasdaq.com/api/screener/stocks\\?tableonly\\=true\\&limit\\=25\\&offset\\=0\\&exchange\\=nyse\\&download\\=true > /tmp/nyse.json"
      - name: gen-nyse-stock-tickers-json
        run: "cat /tmp/nyse.json | jq '.data.rows' > $GITHUB_WORKSPACE/datafiles/nyse/nyse_full_tickers-${{ env.DATE }}.json"

      # Generate AMEX Data
      - name: make-amex-directory
        run: mkdir -p $GITHUB_WORKSPACE/amex
      - name: get-amex
        run: "curl --user-agent 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:85.0) Gecko/20100101 Firefox/85.0' https://api.nasdaq.com/api/screener/stocks\\?tableonly\\=true\\&limit\\=25\\&offset\\=0\\&exchange\\=amex\\&download\\=true > /tmp/amex.json"
      - name: gen-amex-stock-tickers-json
        run: "cat /tmp/amex.json | jq '.data.rows' > $GITHUB_WORKSPACE/datafiles/amex/amex_full_tickers-${{ env.DATE }}.json"

      - name: commit-new-files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
