name: Update artha database with data from the datafiles for a given date

# Controls when the action will run.
on:
  schedule:
    # Run at midnight UTC (4 pm PDT) Mon thru Fri
    - cron: "30 22 * * 1-5"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      # set the current date in environment to be used for appending to filenames in subsequent steps
      - name: current-date
        run: echo "DATE='2025-09-10'" >> $GITHUB_ENV

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Setup caching of the virtual environment directory
      #- name: Cache virtual environment
        #id: cache-venv
        #uses: actions/cache@v4
        #with:
          #path: .venv
          #key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }} # Unique key for the cache
          #restore-keys: |
            #${{ runner.os }}-venv-
            #${{ runner.os }}-

      # Create a virtual environment and activate it
      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          echo "PATH=${GITHUB_WORKSPACE}/.venv/bin:$PATH" >> $GITHUB_ENV

      # Install dependencies in the virtual environment, if cache miss
      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          pip install -r requirements.txt

      # Run database update script
      - name: execute-db-update
        run: |
          echo "Github_workspace: $GITHUB_WORKSPACE"
          echo "Gitub_env: $GITHUB_ENV"
          echo "$GITHUB_WORKSPACE/scripts/update_db.sh ${{ env.DATE }}"
          echo "Path: $PATH"
          echo "env.path: ${{ env.PATH }}"
          which python
